// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Analyzes song lyrics to extract key information.
 *
 * - analyzeSongContent - A function that analyzes song lyrics.
 * - AnalyzeSongContentInput - The input type for the analyzeSongContent function.
 * - AnalyzeSongContentOutput - The return type for the analyzeSongContent function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const AnalyzeSongContentInputSchema = z.object({
  lyrics: z.string().describe('The lyrics of the song to analyze.'),
});
export type AnalyzeSongContentInput = z.infer<typeof AnalyzeSongContentInputSchema>;

const AnalyzeSongContentOutputSchema = z.object({
  summary: z.string().describe('A brief summary of the song.'),
  themes: z.array(z.string()).describe('The main themes explored in the song.'),
  punchlines: z.array(z.string()).describe('The most impactful punchlines in the song.'),
  mood: z.string().describe('The overall mood or feeling conveyed by the song.'),
  structure: z.string().describe('The structure of the song (e.g., verse, chorus, bridge).'),
  culturalReferences: z
    .array(z.string())
    .describe('Any cultural references present in the song.'),
    similarSongs: z.array(z.string()).describe('A list of similar songs based on the analysis.'), // Added similarSongs
});
export type AnalyzeSongContentOutput = z.infer<typeof AnalyzeSongContentOutputSchema>;

export async function analyzeSongContent(input: AnalyzeSongContentInput): Promise<AnalyzeSongContentOutput> {
  return analyzeSongContentFlow(input);
}

const analyzeSongContentPrompt = ai.definePrompt({
  name: 'analyzeSongContentPrompt',
  input: {
    schema: z.object({
      lyrics: z.string().describe('The lyrics of the song to analyze.'),
    }),
  },
  output: {
    schema: AnalyzeSongContentOutputSchema,
  },
  prompt: `Analyze the following song lyrics and extract key information.  Provide the information in the requested JSON format. Make sure the themes, punchlines and culturalReferences are JSON arrays. Also include a list of similar songs based on your analysis.

Lyrics:
{{{lyrics}}}

Summary:
Theme:
Top punchlines:
Mood:
Structure:
Cultural significance:
Similar songs:
`,
});

const analyzeSongContentFlow = ai.defineFlow<
  typeof AnalyzeSongContentInputSchema,
  typeof AnalyzeSongContentOutputSchema
>(
  {
    name: 'analyzeSongContentFlow',
    inputSchema: AnalyzeSongContentInputSchema,
    outputSchema: AnalyzeSongContentOutputSchema,
  },
  async input => {
    const {output} = await analyzeSongContentPrompt(input);
    return output!;
  }
);
